### PR TITLE
Fixed the sentry tags in raven-lua and also add raven-lua version

### LINKED ISSUE #12: Discarded invalid value for parameter 'tags'
In the project home page's README synopsis, [the example](https://github.com/cloudflare/raven-lua/blob/master/README.md#synopsis) code to initialize `rvn` reads:

``` lua
    -- http://pub:secret@127.0.0.1:8080/sentry/proj-id
    local rvn = raven:new("http://pub:secret@127.0.0.1:8080/sentry/proj-id", {
       tags = { foo = "bar" },
    })
    ...
```

However, it turns out that `tags` parameter doesn't seem to be legal. As seen in Sentry logs:
screen shot 2016-04-11 at 11 01 27 am

Sentry on-premise backend version is `8.3.1`.

### PR DESCRIPTION
**Pull request by ye**
The sentry context tags table structure might have been changed since last time raven-lua was released.

Fix the error on the Sentry on-premise and add [the current sentry protocol version, which is '7'](https://docs.getsentry.com/on-premise/clientdev/#authentication) and client version in the signature.

All unit tests passed and running against an on-premise Sentry backend gets corrected results on tags now.

This should resolve #12

### CODE REVIEW

**Comment by dndx** [comment]
Hello @ye, thanks for your PR, can you please rebase to the latest master so that Travis can run your tests?

**Comment by ye** [comment]
@dndx Thanks for your response. I would, except that I think it's up-to-date already. Is there any other way to trigger travis manually?


```bash
$ git co fix-event-tags-and-add-client-version 
Switched to branch 'fix-event-tags-and-add-client-version'
Your branch is ahead of 'github/master' by 1 commit.
  (use "git push" to publish your local commits)
$ git rebase github/master
Current branch fix-event-tags-and-add-client-version is up to date.
```

File: raven.lua [hunk 1]
```diff
@@ -484,7 +485,7 @@ function _M.gen_capture_err(self)
 end
 
 -- HTTP request template
-local xsentryauth_http = "POST %s HTTP/1.0\r\nHost: %s\r\nConnection: close\r\nContent-Type: application/json\r\nContent-Length: %d\r\nUser-Agent: %s\r\nX-Sentry-Auth: Sentry sentry_version=5, sentry_client=%s, sentry_timestamp=%s, sentry_key=%s, sentry_secret=%s\r\n\r\n%s"
+local xsentryauth_http = "POST %s HTTP/1.0\r\nHost: %s\r\nConnection: close\r\nContent-Type: application/json\r\nContent-Length: %d\r\nUser-Agent: %s\r\nX-Sentry-Auth: Sentry sentry_version=7, sentry_client=%s, sentry_timestamp=%s, sentry_key=%s, sentry_secret=%s\r\n\r\n%s"
```
Comment (dndx) [inline raven.lua]: Here, looks like latest `raven-python` and `raven-php` are both using protocol `6`. Any reason to use protocol `7` here?

Comment (ye) [inline raven.lua]: `sentry_version` is the expected Sentry server version that raven client talks to. At the time when I submitted my PR six month ago, the Sentry server version was at 7.x, now it's at 8.x. So IMMO it should in fact be 8 now, pending testing with latest 8.x version. (I did test again Sentry 7.x server back then.) However, I don't think that matters as the unit tests are using different versions all over the place in both server side and client side codebase.

I've open a ticket https://github.com/getsentry/raven-python/issues/908 to ask Sentry guys to clarify this. I don't the `sentry_version` actually matters if you are putting it as 5 or 6 or 7 or 8. But if you insist, I can make it to 6.

Comment (mattrobenolt) [inline raven.lua]: To jump in here, there's not really a reason to bump the version here unless it's leveraging a feature of the newer protocol versions. This version doesn't correlate directly to the major version of Sentry server, and arbitrarily bumping it to `7` will break compatibility on older versions of the server for potentially no reason.

But, if you did bump it to `8`, it would 100% stop working since we don't have a protocol version 8 and all events would get rejected.

Comment (ye) [inline raven.lua]: @mattrobenolt thanks to chime in! @dndx is '6' ok? If not, I am reverting it back...again 😂

Comment (ye) [inline raven.lua]: @dndx 15aeb1d updated the api protocol to be `6` which is in line with other sentry clients and @mattrobenolt ok'd it. And Travis CI build passed. Can we move along with this PR?

**Comment by ye** [comment]
Looks like this PR would solve #5 as well.
